language: go
sudo: required
services:
  - docker
go:
- 1.8
before_install:
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
os:
- linux
script:
- go build -race
- go test -v ./...
- go vet
env:
  global:
  - COMMIT=${TRAVIS_COMMIT}

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=dougefresh/ftp-passwd-pot
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$COMMIT
  - docker push $REPO
