sudo: required
services:
- docker
os:
- linux
script:
- echo ${TRAVIS_COMMIT}
env:
  global:
  - COMMIT=${TRAVIS_COMMIT}
  - secure: t4PPfZ20rxIsrYAhsBerxe+GjesXUmcAuvVI8pzG5017yIv4G5JIB4Mzne5nT6jMi2p7w1T94c3zesDPyqK0OaXu/YsUqr+4UpU0+Zvz1YW2mcPwzIkWMSeKsf67LfWxixdhjq9DwhfRPYKhRW+a0zt/hGN7wLnYvMdnQn+XoLj5rv7DIZ8zN3uPw9dVDStN+1Pm08meo3q9zQu2Zi9NUUz4TyF3VWkMxKFqR/bBmeX+HV6NUslBgY9UwjDjMvlXZZrKVzWP2Vc+dN84cy7fzILXeqQScvrgg1y5yH9kAF0SpHmS43n9I/hrii9MBy54TPhm2P+BR5Wl/AUM8Nw2mprLx4l+I/yF9dR+hOCKIoNzbeobZkxNo8W5f2FLkXKmrwvXtQr9ojKiVLEsCignxATdfx4k90KsjH/tK6Jp8hhgkEK3STJCZNJj/O37GkEhhoD9Wko7A+1+oMykUa5pZ6VtRxIxERGY978TRercKYsWuSH6JzJhfZUqhBBU1RsZ9ZClUl2ql8iu8zlH14+GEh2T34WZLSfaxlBtGU9Qp/Kalouf7TXeLhxPhj2Rn+hZHHfklcJ5UDJ442kjsZeWSj9QLqLTUrfrPAB7eJnMcs+UgGEp+NfeBg4jxWsyj93jk9lOnIhcq6EgeNWNMIMvY8bfeCUopChI26NsNJVYqC0=
  - secure: G25hHQnWLuGHK2WlE2qZpKT1SqiwRni3Dp7qXT/NwLJ68uqLhYsiSqm/z9q5+kavRheuHoyx09uscLQI5qmt5JLPhwme0ILUQVrREL6TatJPheJ6OAYyAVFgCK9kV+rSoQJ2A1qNtFrMizCkbdScgR27MwzNnQyl3YVYcAtUlzoiIDkLOFKecGnjZajeTGm1ok4xlLTqr/e7JGC/o3OwREJhyljBAy7UcFSDpTnoB1ABAfNop9/wEWsnUKxGvKIumZfN25rxyTNlxS4AtMdSAmUdr11un5eOQX7UbW+6l6O1TwotkOvwmj8R5sVAm+3AC/JOhATBgs0RX0dEdQPKidg9Bo2H6+kTFTAmmirJEQBJI94VtU+ndYLESbz+U0eOqhUWfmn0PxV3NmvK0ciGI8kl5sDxaxWT8iyB9cZ4HtcOUgbWAt+PAL34NUWcLMWo4g78yu4xl9Ccczpb7m2uoMRKh2NwUugROd6O5fj7mKamv7NdCvjPGj3ZGINARjZ+v9DDNc0ZDRJkIWS7qWqEzfqWS9kMZOwM43o+1Vvy568Ve6JQEnd9kdwokRSP8NqgIZbV9VMNL/fESvlhWMfdTF5TLFmf5KiJRuAMXTRwWl8B7Dhic8qEXDoJSQ1vJad4RTEbw5CSCxakR9hLDlHGyaeApEiUKmHH5xHrRcntAtE=
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=dougefresh/docker-passwd-pot
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$COMMIT
- docker push $REPO:$COMMIT
